# Issues with CORDEX-CMIP5

List of issues with the CORDEX-CMIP5 data from the CDS. 

Some questions:
* Should someone create an Errata entry about [1] and [4]?
* Are [2] and [3] due to an issue with the C3S copy or manifest file, or is the data simply not available?
* Is [7] only corrupted in the C3S copy, or also in the original?


## [1] (extension of original report)

* eur11-hist-day-ichec_ec_earth-clmcom_clm_cclm4_8_17-r12i1p1
* eur11-hist-day-mohc_hadgem2_es-clmcom_clm_cclm4_8_17-r1i1p1
* eur11-hist-day-mpi_m_mpi_esm_lr-clmcom_clm_cclm4_8_17-r1i1p1
* eur11-rcp45-day-ichec_ec_earth-clmcom_clm_cclm4_8_17-r12i1p1
* eur11-rcp45-day-mohc_hadgem2_es-clmcom_clm_cclm4_8_17-r1i1p1
* eur11-rcp45-day-mpi_m_mpi_esm_lr-clmcom_clm_cclm4_8_17-r1i1p1
* eur11-rcp85-day-ichec_ec_earth-clmcom_clm_cclm4_8_17-r12i1p1
* eur11-rcp85-day-mohc_hadgem2_es-clmcom_clm_cclm4_8_17-r1i1p1
* eur11-rcp85-day-mpi_m_mpi_esm_lr-clmcom_clm_cclm4_8_17-r1i1p1

They all share the same regional model, CLMcom-CLM-CCLM4-8-17, and with different realisations: r12i1p1, r1i1p1. The anomaly occurs in the following variables: clt, rlds, ps, rsus, which show extremely high and low values.
 
## [2] 

* eur11-hist-day-mohc_hadgem2_es-knmi_racmo22e-r1i1p1 

Missing rlds variable (surface downwelling longwave flux) data for 1981-1985.
 
## [3] 

* eur11-rcp85-day-ichec_ec_earth-dmi_hirham5-r3i1p1 

Missing huss (specific humidity) data for 1971-1975.
 
## [4] 

* eur11-rcp85-day-ichec_ec_earth-uhoh_wrf361h-r12i1p1 
* eur11-rcp85-day-mohc_hadgem2_es-uhoh_wrf361h-r1i1p1
* eur11-rcp85-day-mpi_m_mpi_esm_lr-uhoh_wrf361h-r1i1p1

Very large values for several dates in huss, ps.
 
## [5] 

* eur11-hist-day-mpi_m_mpi_esm_lr-ipsl_wrf381p-r1i1p1 
* eur11-rcp85-day-mpi_m_mpi_esm_lr-ipsl_wrf381p-r1i1p1

Invalid x, y coordinates: all 0’s
 
## [6]

* eur11-hist-day-miroc_miroc5-uhoh_wrf361h-r1i1p1
  
Missing projection information at least for rsds and the 1970 file, maybe also in other variables/files.

Similarly:

*   eur11-rcp85-day-miroc_miroc5-uhoh_wrf361h-r1i1p1

Missing projection information at least _ for _huss and the 2006-2010 file, maybe also in other variables/files.
 
## [7]

* eur11-hist-6h-mohc_hadgem2_es-cnrm_aladin63-r1i1p1
  
Data for mrro seems corrupted for at least the 1950 file ("NetCDF: HDF error" thrown when reading daily sample #60 (0-based))

## Load catalog

In [1]:
import intake

In [2]:
cat_url = "https://raw.githubusercontent.com/cp4cds/c3s_34g_manifests/master/intake/catalogs/c3s.yaml"

cat = intake.open_catalog(cat_url)
list(cat)

['c3s-cmip5',
 'c3s-cmip5-daily-pressure-level',
 'c3s-cmip5-daily-single-level',
 'c3s-cmip5-monthly-pressure-level',
 'c3s-cmip5-monthly-single-level',
 'c3s-cmip6',
 'c3s-cmip6-decadal',
 'c3s-cordex',
 'c3s-ipcc-atlas',
 'c3s-cica-atlas-v01',
 'c3s-cica-atlas']

In [3]:
df_cordex = cat['c3s-cordex'].read()
df_cordex

ds_id  \
0       c3s-cordex.output.EAS-44.CLMcom.CNRM-CERFACS-C...   
1       c3s-cordex.output.EAS-44.CLMcom.CNRM-CERFACS-C...   
2       c3s-cordex.output.EAS-44.CLMcom.CNRM-CERFACS-C...   
3       c3s-cordex.output.EAS-44.CLMcom.CNRM-CERFACS-C...   
4       c3s-cordex.output.EAS-44.CLMcom.CNRM-CERFACS-C...   
...                                                   ...   
567374  c3s-cordex.output.CAM-44.SMHI.ICHEC-EC-EARTH.h...   
567375  c3s-cordex.output.CAM-44.SMHI.ICHEC-EC-EARTH.h...   
567376  c3s-cordex.output.CAM-44.SMHI.ICHEC-EC-EARTH.h...   
567377  c3s-cordex.output.CAM-44.SMHI.ICHEC-EC-EARTH.h...   
567378  c3s-cordex.output.CAM-44.SMHI.ICHEC-EC-EARTH.h...   

                                                     path       size  \
0       output/EAS-44/CLMcom/CNRM-CERFACS-CNRM-CM5/rcp...  176452637   
1       output/EAS-44/CLMcom/CNRM-CERFACS-CNRM-CM5/rcp...  176393262   
2       output/EAS-44/CLMcom/CNRM-CERFACS-CNRM-CM5/rcp...  176557045   
3       output/EAS-44/CLMcom/CNRM-CERFACS-CNRM-CM5/rcp...  176346476   
4       output/EAS-44/CLMcom/CNRM-CERFACS-CNRM-CM5/rcp...  176260737   
...                                                   ...        ...   
567374  output/CAM-44/SMHI/ICHEC-EC-EARTH/historical/r...   60776141   
567375  output/CAM-44/SMHI/ICHEC-EC-EARTH/historical/r...   60562273   
567376  output/CAM-44/SMHI/ICHEC-EC-EARTH/historical/r...   60779301   
567377  output/CAM-44/SMHI/ICHEC-EC-EARTH/historical/r...   60957749   
567378  output/CAM-44/SMHI/ICHEC-EC-EARTH/historical/r...   60801923   

           project product  domain institute          driving_model  \
0       c3s-cordex  output  EAS-44    CLMcom  CNRM-CERFACS-CNRM-CM5   
1       c3s-cordex  output  EAS-44    CLMcom  CNRM-CERFACS-CNRM-CM5   
2       c3s-cordex  output  EAS-44    CLMcom  CNRM-CERFACS-CNRM-CM5   
3       c3s-cordex  output  EAS-44    CLMcom  CNRM-CERFACS-CNRM-CM5   
4       c3s-cordex  output  EAS-44    CLMcom  CNRM-CERFACS-CNRM-CM5   
...            ...     ...     ...       ...                    ...   
567374  c3s-cordex  output  CAM-44      SMHI         ICHEC-EC-EARTH   
567375  c3s-cordex  output  CAM-44      SMHI         ICHEC-EC-EARTH   
567376  c3s-cordex  output  CAM-44      SMHI         ICHEC-EC-EARTH   
567377  c3s-cordex  output  CAM-44      SMHI         ICHEC-EC-EARTH   
567378  c3s-cordex  output  CAM-44      SMHI         ICHEC-EC-EARTH   

       experiment_id ensemble          rcm_name rcm_version time_frequency  \
0              rcp45   r1i1p1  CLMcom-CCLM5-0-2          v1            day   
1              rcp45   r1i1p1  CLMcom-CCLM5-0-2          v1            day   
2              rcp45   r1i1p1  CLMcom-CCLM5-0-2          v1            day   
3              rcp45   r1i1p1  CLMcom-CCLM5-0-2          v1            day   
4              rcp45   r1i1p1  CLMcom-CCLM5-0-2          v1            day   
...              ...      ...               ...         ...            ...   
567374    historical  r12i1p1         SMHI-RCA4          v1            day   
567375    historical  r12i1p1         SMHI-RCA4          v1            day   
567376    historical  r12i1p1         SMHI-RCA4          v1            day   
567377    historical  r12i1p1         SMHI-RCA4          v1            day   
567378    historical  r12i1p1         SMHI-RCA4          v1            day   

       variable    version           start_time             end_time  \
0          huss  v20201215  2006-01-01T12:00:00  2010-12-31T12:00:00   
1          huss  v20201215  2011-01-01T12:00:00  2015-12-31T12:00:00   
2          huss  v20201215  2016-01-01T12:00:00  2020-12-31T12:00:00   
3          huss  v20201215  2021-01-01T12:00:00  2025-12-31T12:00:00   
4          huss  v20201215  2026-01-01T12:00:00  2030-12-31T12:00:00   
...         ...        ...                  ...                  ...   
567374   tasmin  v20201201  1981-01-01T12:00:00  1985-12-31T12:00:00   
567375   tasmin  v20201201  1986-01-01T12:00:00  1990-12-31T12:00:00   
567376   tasmin 

## Issue [2] 

eur11-hist-day-mohc_hadgem2_es-knmi_racmo22e-r1i1p1

Missing rlds variable (surface downwelling longwave flux) data for 1981-1985.

In [4]:
# [2] eur11-hist-day-mohc_hadgem2_es-knmi_racmo22e-r1i1p1

df_2 = df_cordex.loc[
    (df_cordex.variable=="rlds") 
    & (df_cordex.experiment_id=="historical")
    & (df_cordex.rcm_name=="KNMI-RACMO22E")
    & (df_cordex.domain=="EUR-11")
    & (df_cordex.time_frequency=="day")
    & (df_cordex.driving_model=="MOHC-HadGEM2-ES")
    & (df_cordex.ensemble=="r1i1p1")
]
df_2.head()

ds_id  \
327837  c3s-cordex.output.EUR-11.KNMI.MOHC-HadGEM2-ES....   
327838  c3s-cordex.output.EUR-11.KNMI.MOHC-HadGEM2-ES....   
327839  c3s-cordex.output.EUR-11.KNMI.MOHC-HadGEM2-ES....   
327840  c3s-cordex.output.EUR-11.KNMI.MOHC-HadGEM2-ES....   
327841  c3s-cordex.output.EUR-11.KNMI.MOHC-HadGEM2-ES....   

                                                     path       size  \
327837  output/EUR-11/KNMI/MOHC-HadGEM2-ES/historical/...  154588846   
327838  output/EUR-11/KNMI/MOHC-HadGEM2-ES/historical/...  766117778   
327839  output/EUR-11/KNMI/MOHC-HadGEM2-ES/historical/...  765334038   
327840  output/EUR-11/KNMI/MOHC-HadGEM2-ES/historical/...  766504656   
327841  output/EUR-11/KNMI/MOHC-HadGEM2-ES/historical/...  765524191   

           project product  domain institute    driving_model experiment_id  \
327837  c3s-cordex  output  EUR-11      KNMI  MOHC-HadGEM2-ES    historical   
327838  c3s-cordex  output  EUR-11      KNMI  MOHC-HadGEM2-ES    historical   
327839  c3s-cordex  output  EUR-11      KNMI  MOHC-HadGEM2-ES    historical   
327840  c3s-cordex  output  EUR-11      KNMI  MOHC-HadGEM2-ES    historical   
327841  c3s-cordex  output  EUR-11      KNMI  MOHC-HadGEM2-ES    historical   

       ensemble       rcm_name rcm_version time_frequency variable    version  \
327837   r1i1p1  KNMI-RACMO22E          v2            day     rlds  v20160620   
327838   r1i1p1  KNMI-RACMO22E          v2            day     rlds  v20160620   
327839   r1i1p1  KNMI-RACMO22E          v2            day     rlds  v20160620   
327840   r1i1p1  KNMI-RACMO22E          v2            day     rlds  v20160620   
327841   r1i1p1  KNMI-RACMO22E          v2            day     rlds  v20160620   

                 start_time             end_time                         bbox  \
327837  1950-01-01T12:00:00  1950-12-30T12:00:00  -44.59, 21.99, 64.96, 72.58   
327838  1951-01-01T12:00:00  1955-12-30T12:00:00  -44.59, 21.99, 64.96, 72.58   
327839  1956-01-01T12:00:00  1960-12-30T12:00:00  -44.59, 21.99, 64.96, 72.58   
327840  1961-01-01T12:00:00  1965-12-30T12:00:00  -44.59, 21.99, 64.96, 72.58   
327841  1966-01-01T12:00:00  1970-12-30T12:00:00  -44.59, 21.99, 64.96, 72.58   

       level  
327837   NaN  
327838   NaN  
327839   NaN  
327840   NaN  
327841   NaN

In [5]:
start_time = list(df_2.start_time.unique())
start_time.sort()
start_time

['1950-01-01T12:00:00',
 '1951-01-01T12:00:00',
 '1956-01-01T12:00:00',
 '1961-01-01T12:00:00',
 '1966-01-01T12:00:00',
 '1971-01-01T12:00:00',
 '1976-01-01T12:00:00',
 '1986-01-01T12:00:00',
 '1991-01-01T12:00:00',
 '1996-01-01T12:00:00',
 '2001-01-01T12:00:00']

In [6]:
end_time = list(df_2.end_time.unique())
end_time.sort()
end_time

['1950-12-30T12:00:00',
 '1955-12-30T12:00:00',
 '1960-12-30T12:00:00',
 '1965-12-30T12:00:00',
 '1970-12-30T12:00:00',
 '1975-12-30T12:00:00',
 '1980-12-30T12:00:00',
 '1990-12-30T12:00:00',
 '1995-12-30T12:00:00',
 '2000-12-30T12:00:00',
 '2005-12-30T12:00:00']

In [7]:
list(df_2.rcm_name.unique())

['KNMI-RACMO22E']

In [8]:
list(df_2.path.unique())

['output/EUR-11/KNMI/MOHC-HadGEM2-ES/historical/r1i1p1/KNMI-RACMO22E/v2/day/rlds/v20160620/rlds_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_KNMI-RACMO22E_v2_day_19500101-19501230.nc',
 'output/EUR-11/KNMI/MOHC-HadGEM2-ES/historical/r1i1p1/KNMI-RACMO22E/v2/day/rlds/v20160620/rlds_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_KNMI-RACMO22E_v2_day_19510101-19551230.nc',
 'output/EUR-11/KNMI/MOHC-HadGEM2-ES/historical/r1i1p1/KNMI-RACMO22E/v2/day/rlds/v20160620/rlds_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_KNMI-RACMO22E_v2_day_19560101-19601230.nc',
 'output/EUR-11/KNMI/MOHC-HadGEM2-ES/historical/r1i1p1/KNMI-RACMO22E/v2/day/rlds/v20160620/rlds_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_KNMI-RACMO22E_v2_day_19610101-19651230.nc',
 'output/EUR-11/KNMI/MOHC-HadGEM2-ES/historical/r1i1p1/KNMI-RACMO22E/v2/day/rlds/v20160620/rlds_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_KNMI-RACMO22E_v2_day_19660101-19701230.nc',
 'output/EUR-11/KNMI/MOHC-HadGEM2-ES/historical/r1i1p1/KNMI-RACMO22E/v2/day/rlds/v20160620/rlds

### check on disk

```
ls -l output/EUR-11/KNMI/MOHC-HadGEM2-ES/historical/r1i1p1/KNMI-RACMO22E/v2/day/rlds/v20160620
total 7633768
-rw-r--r--. 1 k204199 ik1017 154588846 Sep 13  2021 rlds_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_KNMI-RACMO22E_v2_day_19500101-19501230.nc
-rw-r--r--. 1 k204199 ik1017 766117778 Sep 13  2021 rlds_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_KNMI-RACMO22E_v2_day_19510101-19551230.nc
-rw-r--r--. 1 k204199 ik1017 765334038 Sep 13  2021 rlds_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_KNMI-RACMO22E_v2_day_19560101-19601230.nc
-rw-r--r--. 1 k204199 ik1017 766504656 Jan 26  2020 rlds_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_KNMI-RACMO22E_v2_day_19610101-19651230.nc
-rw-r--r--. 1 k204199 ik1017 765524191 Sep 13  2021 rlds_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_KNMI-RACMO22E_v2_day_19660101-19701230.nc
-rw-r--r--. 1 k204199 ik1017 766009746 Sep 13  2021 rlds_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_KNMI-RACMO22E_v2_day_19710101-19751230.nc
-rw-r--r--. 1 k204199 ik1017 764979219 Sep 13  2021 rlds_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_KNMI-RACMO22E_v2_day_19760101-19801230.nc
-rw-r--r--. 1 k204199 ik1017   8388608 Sep 13  2021 rlds_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_KNMI-RACMO22E_v2_day_19810101-19851230.nc
-rw-r--r--. 1 k204199 ik1017 764348850 Sep 13  2021 rlds_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_KNMI-RACMO22E_v2_day_19860101-19901230.nc
-rw-r--r--. 1 k204199 ik1017 766102908 Sep 13  2021 rlds_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_KNMI-RACMO22E_v2_day_19910101-19951230.nc
-rw-r--r--. 1 k204199 ik1017 763787382 Sep 13  2021 rlds_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_KNMI-RACMO22E_v2_day_19960101-20001230.nc
-rw-r--r--. 1 k204199 ik1017 765224568 Sep 13  2021 rlds_EUR-11_MOHC-HadGEM2-ES_historical_r1i1p1_KNMI-RACMO22E_v2_day_20010101-20051230.nc
    ```

## Issue [3] 

* eur11-rcp85-day-ichec_ec_earth-dmi_hirham5-r3i1p1 

Missing huss (specific humidity) data for 1971-1975.

In [9]:
# [2] eur11-rcp85-day-ichec_ec_earth-dmi_hirham5-r3i1p1

df_3 = df_cordex.loc[
    (df_cordex.variable=="huss") 
    & (df_cordex.experiment_id=="historical")
    # & (df_cordex.experiment_id=="rcp85")
    # & (df_cordex.institute=="MOHC")
    & (df_cordex.domain=="EUR-11")
    & (df_cordex.time_frequency=="day")
    & (df_cordex.driving_model=="ICHEC-EC-EARTH")
    & (df_cordex.rcm_name=="DMI-HIRHAM5")
    & (df_cordex.ensemble=="r3i1p1")
]
df_3.head()

ds_id  \
535158  c3s-cordex.output.EUR-11.DMI.ICHEC-EC-EARTH.hi...   
535159  c3s-cordex.output.EUR-11.DMI.ICHEC-EC-EARTH.hi...   
535160  c3s-cordex.output.EUR-11.DMI.ICHEC-EC-EARTH.hi...   
535161  c3s-cordex.output.EUR-11.DMI.ICHEC-EC-EARTH.hi...   
535162  c3s-cordex.output.EUR-11.DMI.ICHEC-EC-EARTH.hi...   

                                                     path       size  \
535158  output/EUR-11/DMI/ICHEC-EC-EARTH/historical/r3...  519416520   
535159  output/EUR-11/DMI/ICHEC-EC-EARTH/historical/r3...  519006978   
535160  output/EUR-11/DMI/ICHEC-EC-EARTH/historical/r3...  520171775   
535161  output/EUR-11/DMI/ICHEC-EC-EARTH/historical/r3...  517086295   
535162  output/EUR-11/DMI/ICHEC-EC-EARTH/historical/r3...  519233577   

           project product  domain institute   driving_model experiment_id  \
535158  c3s-cordex  output  EUR-11       DMI  ICHEC-EC-EARTH    historical   
535159  c3s-cordex  output  EUR-11       DMI  ICHEC-EC-EARTH    historical   
535160  c3s-cordex  output  EUR-11       DMI  ICHEC-EC-EARTH    historical   
535161  c3s-cordex  output  EUR-11       DMI  ICHEC-EC-EARTH    historical   
535162  c3s-cordex  output  EUR-11       DMI  ICHEC-EC-EARTH    historical   

       ensemble     rcm_name rcm_version time_frequency variable    version  \
535158   r3i1p1  DMI-HIRHAM5          v2            day     huss  v20190212   
535159   r3i1p1  DMI-HIRHAM5          v2            day     huss  v20190212   
535160   r3i1p1  DMI-HIRHAM5          v2            day     huss  v20190212   
535161   r3i1p1  DMI-HIRHAM5          v2            day     huss  v20190212   
535162   r3i1p1  DMI-HIRHAM5          v2            day     huss  v20190212   

                 start_time             end_time                         bbox  \
535158  1951-01-01T12:00:00  1955-12-31T12:00:00  -44.59, 21.99, 64.96, 72.58   
535159  1956-01-01T12:00:00  1960-12-31T12:00:00  -44.59, 21.99, 64.96, 72.58   
535160  1961-01-01T12:00:00  1965-12-31T12:00:00  -44.59, 21.99, 64.96, 72.58   
535161  1966-01-01T12:00:00  1970-12-31T12:00:00  -44.59, 21.99, 64.96, 72.58   
535162  1971-01-01T12:00:00  1975-12-31T12:00:00  -44.59, 21.99, 64.96, 72.58   

       level  
535158  2.00  
535159  2.00  
535160  2.00  
535161  2.00  
535162  2.00

In [10]:
start_time = list(df_3.start_time.unique())
start_time.sort()
start_time

['1951-01-01T12:00:00',
 '1956-01-01T12:00:00',
 '1961-01-01T12:00:00',
 '1966-01-01T12:00:00',
 '1971-01-01T12:00:00',
 '1976-01-01T12:00:00',
 '1981-01-01T12:00:00',
 '1986-01-01T12:00:00',
 '1991-01-01T12:00:00',
 '1996-01-01T12:00:00',
 '2001-01-01T12:00:00']

In [11]:
end_time = list(df_3.end_time.unique())
end_time.sort()
end_time

['1955-12-31T12:00:00',
 '1960-12-31T12:00:00',
 '1965-12-31T12:00:00',
 '1970-12-31T12:00:00',
 '1975-12-31T12:00:00',
 '1980-12-31T12:00:00',
 '1985-12-31T12:00:00',
 '1990-12-31T12:00:00',
 '1995-12-31T12:00:00',
 '2000-12-31T12:00:00',
 '2005-12-31T12:00:00']