# conda env update -f environment.yml
name: rooki
channels:
  - conda-forge
dependencies:
  - pip
  - ipython
  - jupyterlab
  - ipywidgets
  - nodejs
  - xarray>=0.15
  - netcdf4
  - pip:
    - -e git+https://github.com/cehbrecht/pymetalink.git@patched#egg=metalink
